# ================================
# FILE: monitoring/prometheus.yml
# ================================

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'voice-cloning-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s